import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans ;- yes there is diffrence in the data type of variables list_ and array_list

In [4]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
for i in list_:
    print(i)
print(" ")
for i in array_list:
    print(i)

1
2
3
4
5
 
1
2
3
4
5


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [13]:
array_list = np.array(object = list_, dtype = int)
print(type(array_list))
print(type(array_list[0]))
# yes  there is a difference in the data type of the elements present in both the variables

<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

In [15]:
num_array.shape

(2, 3)

In [16]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [21]:
array_matrix=np.random.randint(0,1,(3,3))

In [22]:
print(array_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
